export type Lang = 'sw' | 'en';

export const LANG_LABELS: Record<Lang, string> = {
  sw: 'Kiswahili',
  en: 'English',
};

const dict = {
  // ── Nav ──────────────────────────────────────────────────────────────────────
  nav_product:  { sw: 'Bidhaa',    en: 'Product'  },
  nav_ai:       { sw: 'Ziada AI',  en: 'Ziada AI' },
  nav_pricing:  { sw: 'Bei',       en: 'Pricing'  },
  nav_about:    { sw: 'Kuhusu',    en: 'About'    },
  nav_contact:  { sw: 'Wasiliana', en: 'Contact'  },
  nav_signin:   { sw: 'Ingia',     en: 'Sign in'  },

  // ── Dots menu ─────────────────────────────────────────────────────────────────
  dots_appearance: { sw: 'MUONEKANO', en: 'APPEARANCE' },
  dots_language:   { sw: 'LUGHA',     en: 'LANGUAGE'   },
  dots_light:      { sw: 'Mwanga',    en: 'Light'       },
  dots_dark:       { sw: 'Giza',      en: 'Dark'        },

  // ── Hero ─────────────────────────────────────────────────────────────────────
  hero_badge:      { sw: 'Ziada AI · sasa kila duka',             en: 'Ziada AI · now in every store'            },
  hero_h1a:        { sw: 'Mfumo wa uendeshaji',                   en: 'The operating system'                     },
  hero_h1b:        { sw: 'wa duka lako.',                         en: 'for your shop.'                           },
  hero_sub:        { sw: 'POS, bidhaa, mikopo, uchambuzi na AI inayojua duka lako — mfumo mmoja, wa haraka. Ilijengwa Tanzania, kwa kila kaunta.',
                     en: 'POS, inventory, credit, analytics and an AI that actually knows your store — running on one calm, fast platform. Built in Tanzania, made for any counter.' },
  hero_trial:      { sw: 'Anza majaribio',                         en: 'Start trial'                              },
  hero_signin:     { sw: 'Ingia',                                  en: 'Sign in'                                  },
  hero_trust1:     { sw: 'kadi haihitajiki',                       en: 'no card required'                         },
  hero_trust2:     { sw: 'inafanya kazi bila mtandao',             en: 'works offline'                            },
  hero_trust3:     { sw: 'EN + Kiswahili',                         en: 'EN + Swahili'                             },
  hero_trust4:     { sw: 'M-Pesa, Tigo, Airtel, Benki',           en: 'M-Pesa, Tigo, Airtel, Bank'               },

  // ── Stats ─────────────────────────────────────────────────────────────────────
  stat_stores:     { sw: 'MADUKA YANAYOTUMIA ZIADA',   en: 'STORES RUNNING ZIADA' },
  stat_txns:       { sw: 'MIAMALA 24H ILIYOPITA',      en: 'TXNS LAST 24H'        },
  stat_tzs:        { sw: 'TZS ZILIZOPITA · SIKU 30',   en: 'TZS PROCESSED · 30D'  },
  stat_ai:         { sw: 'MASWALI YA AI · 24H',        en: 'AI QUERIES · 24H'     },
  stat_uptime:     { sw: 'UENDESHAJI · SIKU 90',       en: 'UPTIME · 90D'         },

  // ── Features section header ───────────────────────────────────────────────────
  feat_label:      { sw: '01 · MODULI',                                        en: '01 · MODULES'                          },
  feat_h2:         { sw: 'Jukwaa moja. Sehemu tano. Kila kaunta.',             en: 'One platform. Five surfaces. Every counter.' },
  feat_sub:        { sw: '5 / 5 zimejumuishwa katika kila mpango',             en: '5 / 5 included on every plan'          },

  // POS
  feat_pos_title:  { sw: 'Mauzo',                             en: 'Point of Sale'              },
  feat_pos_tag:    { sw: 'Fanya mauzo kwa mibonyezo mitatu.', en: 'Ring up a sale in three taps.' },
  feat_pos_desc:   { sw: 'Tafuta, skeni, au chagua kutoka kwenye gridi. Pokea pesa taslimu, M-Pesa, Tigo Pesa, Airtel au benki — gawanya kwenye risiti moja.',
                     en: 'Search, scan, or pick from the grid. Take cash, M-Pesa, Tigo Pesa, Airtel or bank — split across any of them on one ticket.' },
  feat_pos_b1:     { sw: 'Nambari ya bidhaa + utafutaji wa picha',   en: 'Barcode + visual search'                       },
  feat_pos_b2:     { sw: 'Malipo ya aina mbalimbali',                en: 'Split tender'                                  },
  feat_pos_b3:     { sw: 'Inafanya kazi bila mtandao, inasawazisha ukiunganika', en: 'Offline-first, syncs when back online' },

  // Inventory
  feat_inv_title:  { sw: 'Hifadhi ya Bidhaa',                   en: 'Inventory'                                  },
  feat_inv_tag:    { sw: 'Jua kilichopo rafu bila kuhesabu.',    en: "Know what's on the shelf without counting." },
  feat_inv_desc:   { sw: 'Hifadhi inasogea kiotomatiki unapouza, kuagiza upya au kuhamisha. Nukta za kuagiza upya na historia ya wasambazaji zinajitokeza kwa kila bidhaa.',
                     en: 'Stock moves automatically as you sell, restock or transfer. Reorder points and supplier history live with each product.' },
  feat_inv_b1:     { sw: 'Nukta za kuagiza upya kiotomatiki',   en: 'Auto reorder points'   },
  feat_inv_b2:     { sw: 'Rejista ya wasambazaji',              en: 'Supplier ledger'        },
  feat_inv_b3:     { sw: 'Bei ya aina na wingi',                en: 'Variant + bulk pricing' },

  // Analytics
  feat_ana_title:  { sw: 'Uchambuzi',                                en: 'Analytics'                     },
  feat_ana_tag:    { sw: 'Mapigo ya moyo ya duka, kila dakika.',     en: "The shop's pulse, every minute." },
  feat_ana_desc:   { sw: 'Mauzo, faida, pembe za faida, mchanganyiko wa malipo na nafasi ya pesa — yote yanaonekana kwa jicho moja, yote yanaweza kuchujwa hadi SKU moja.',
                     en: 'Sales, profit, margins, payment mix and cash position — all visible at a glance, all filterable to a single SKU.' },
  feat_ana_b1:     { sw: 'Mapato kila saa',                en: 'Hour-by-hour revenue'        },
  feat_ana_b2:     { sw: 'Faida kwa bidhaa',               en: 'Profit by product'           },
  feat_ana_b3:     { sw: 'Mtazamo wa wateja wanaorudia',   en: 'Cohort & repeat-customer view' },

  // Credits
  feat_crd_title:  { sw: 'Mikopo',                                 en: 'Credits'                           },
  feat_crd_tag:    { sw: 'Fuatilia kila kopo bila daftari.',       en: 'Track every kopo without a notebook.' },
  feat_crd_desc:   { sw: 'Akaunti wazi, vikumbusho vya malipo, taarifa kupitia WhatsApp. Vikundi vya muda ili ujue daima nani amechelewa.',
                     en: "Open tabs, payment reminders, statements over WhatsApp. Aging buckets so you always know who's overdue." },
  feat_crd_b1:     { sw: 'Vikundi vya mikopo kulingana na muda', en: 'Aging buckets'                },
  feat_crd_b2:     { sw: 'Vikumbusho vya WhatsApp',             en: 'WhatsApp reminders'           },
  feat_crd_b3:     { sw: 'Taarifa ya PDF kwa kibonyezo kimoja',  en: 'Statement PDF in one tap'    },

  // AI module
  feat_ai_title:   { sw: 'Ziada AI',                                    en: 'Ziada AI'                                  },
  feat_ai_tag:     { sw: 'Msaidizi anayejua duka lako kweli kweli.',     en: 'An assistant that actually knows your store.' },
  feat_ai_desc:    { sw: 'Uliza kwa Kiingereza au Kiswahili. Inapata majibu kutoka kwa data yako ya moja kwa moja na inaandaa hatua inayofuata.',
                     en: 'Ask in English or Swahili. Pulls answers from your live data and drafts the next action.'         },
  feat_ai_b1:      { sw: 'Imejengwa kwenye data yako',          en: 'Grounded on your data'              },
  feat_ai_b2:      { sw: 'Lugha mbili EN/SW',                   en: 'Bilingual EN/SW'                    },
  feat_ai_b3:      { sw: 'Inaandika maagizo, ripoti, ujumbe',   en: 'Drafts orders, reports, messages'  },

  // ── AI section ────────────────────────────────────────────────────────────────
  ai_label:        { sw: '02 · ZIADA AI',                                  en: '02 · ZIADA AI'                             },
  ai_h2:           { sw: 'AI ya kwanza inayojua duka lako kweli kweli.',   en: 'The first AI that actually knows your shop.' },
  ai_badge:        { sw: 'imejengwa kwenye data yako · lugha mbili · katika kila skrini', en: 'grounded · bilingual · in every screen' },
  ai_desc:         { sw: 'Msaidizi mwingi wa "AI" ni chatbot tu iliyounganishwa. Ziada AI inasoma mauzo, hifadhi, wasambazaji na mikopo yako ya moja kwa moja — na kuandika jibu. Uliza kwa Kiingereza au Kiswahili na upate jibu na data na hatua inayofuata.',
                     en: 'Most "AI features" are a chatbot bolted on. Ziada AI reads from your live sales, stock, suppliers and credits — and writes back. Ask in English or Swahili and get an answer with data and a next action.' },
  ai_things_label: { sw: 'MAMBO WANAYOULIZA', en: 'THINGS PEOPLE ASK' },
  ai_prop1_t:      { sw: 'Imejengwa',          en: 'Grounded'          },
  ai_prop1_d:      { sw: 'Majibu yanarejelea safu halisi kutoka dukani kwako.', en: 'Answers cite the exact rows from your store.' },
  ai_prop2_t:      { sw: 'Lugha Mbili',         en: 'Bilingual'         },
  ai_prop2_d:      { sw: 'Inasema Kiingereza na Kiswahili, kwa chaguo-msingi.', en: 'Speaks English and Swahili, by default.' },
  ai_prop3_t:      { sw: 'Inachukua Hatua',     en: 'Action-oriented'   },
  ai_prop3_d:      { sw: 'Inaandika agizo la kuagiza, ujumbe, ripoti.',  en: 'Drafts the restock, the message, the report.' },
  ai_prop4_t:      { sw: 'Faragha',             en: 'Private'           },
  ai_prop4_d:      { sw: 'Data yako haifunzi mfano wowote wa AI.',      en: 'Your data never trains a foundation model.'   },

  // AI chat mockup content
  ai_chat_user_q:      { sw: 'Bidhaa 3 zinazouzwa zaidi wiki hii, na zipi zinaisha?',
                          en: 'What were my top 3 fast movers this week, and which are running low?' },
  ai_chat_ai_intro:    { sw: 'Bidhaa zinazouzwa zaidi wiki hii:',       en: 'This week your top movers were:'                              },
  ai_chat_sold:        { sw: 'uuzwa',                                    en: 'sold'                                                         },
  ai_chat_left:        { sw: 'zimebaki',                                 en: 'left'                                                         },
  ai_chat_low:         { sw: 'CHINI',                                    en: 'LOW'                                                          },
  ai_chat_ok:          { sw: 'SAWA',                                     en: 'OK'                                                           },
  ai_chat_critical:    { sw: 'HATARI',                                   en: 'CRITICAL'                                                     },
  ai_chat_reorder:     { sw: 'Sabuni ya OMO iko chini ya kiwango cha kuagiza — niandike agizo la kujaza?',
                          en: 'Sabuni ya OMO is below reorder point — want me to draft a restock order?'  },
  ai_chat_chip1:       { sw: 'Andika agizo',          en: 'Draft restock'        },
  ai_chat_chip2:       { sw: 'Onyesha wasambazaji',   en: 'Show suppliers'       },
  ai_chat_chip3:       { sw: 'Tathmini wiki ijayo',   en: 'Project next week'    },
  ai_chat_input:       { sw: 'Uliza kuhusu duka lako…', en: 'Ask about your store…' },

  // ── Testimonials ─────────────────────────────────────────────────────────────
  test_label:      { sw: 'WAFANYABIASHARA',                    en: 'MERCHANTS'                  },
  test_h2:         { sw: 'Wanachosema wamiliki wa maduka.',    en: 'What store owners say.'     },
  test_count:      { sw: 'Maduka 1,247+ Tanzania',             en: '1,247+ stores in Tanzania'  },
  test_q1:         { sw: '"Ziada ilibadilisha jinsi tunavyofanya biashara. Sasa naona data zangu wakati wowote, hata bila internet."',
                     en: '"Ziada changed how we run our business. I can see my data any time, even without internet."' },
  test_q1_role:    { sw: 'Mmiliki wa Supermarket', en: 'Supermarket owner' },
  test_q2:         { sw: '"Ufuatiliaji wa mikopo peke yake ulinisaidia kuzuia kupoteza TZS 2M katika akaunti ambazo hazijalipiwa. Kila mmiliki wa duka anahitaji hili."',
                     en: '"The credit tracking alone saved me from losing TZS 2M in unpaid tabs. Every duka owner needs this."' },
  test_q2_role:    { sw: 'Duka la Dawa',           en: 'Pharmacy'         },
  test_q3:         { sw: '"Kusimamia maduka 3 kutoka skrini moja — hiyo ilikuwa ndoto. Sasa ni kawaida."',
                     en: '"Managing 3 stores from one screen — that used to be a dream. Now it\'s just Tuesday."' },
  test_q3_role:    { sw: 'Mlolongo wa Maduka',     en: 'Retail chain'     },

  // ── Pricing ──────────────────────────────────────────────────────────────────
  pricing_label:   { sw: '03 · BEI',                                      en: '03 · PRICING'                            },
  pricing_h2:      { sw: 'Bei rahisi, ya kweli. Inalipiwa kwa TZS.',      en: 'Simple, honest pricing. Billed in TZS.'  },
  pricing_see:     { sw: 'Ona bei kamili →',                              en: 'See full pricing →'                      },
  pricing_popular: { sw: 'MAARUFU ZAIDI',                                 en: 'MOST POPULAR'                            },
  pricing_trial:   { sw: 'Anza jaribio bure',                             en: 'Start free trial'                        },
  pricing_contact: { sw: 'Wasiliana nasi',                                en: 'Contact us'                              },
  pricing_foot:    { sw: 'Mipango yote ina majaribio ya siku 7 · Uanzishaji wa TZS 10,000 · Bila kadi · M-Pesa · Tigo · Airtel · Benki',
                     en: 'All plans include a 7-day free trial · TZS 10,000 activation · No credit card · M-Pesa · Tigo · Airtel · Bank' },

  // Plan details (keep plan names in English as product terms)
  plan_starter_target: { sw: 'Maduka ya solo na vibanda',          en: 'Solo dukas and kiosks'         },
  plan_starter_desc:   { sw: 'Kila kitu unachohitaji kuanza kidijitali — POS, bidhaa na ufuatiliaji wa mikopo mahali pamoja.',
                          en: 'Everything you need to go digital — POS, inventory and credit tracking in one place.' },
  plan_biz_target:     { sw: 'Maduka yanayokua na minyororo midogo',  en: 'Growing shops and small chains' },
  plan_biz_desc:       { sw: 'Usimamizi wa maduka mengi, Ziada AI, na uchambuzi wa hali ya juu kwa wafanyabiashara wenye nia.',
                          en: 'Multi-store management, Ziada AI, and advanced analytics for ambitious retailers.' },
  plan_ent_target:     { sw: 'Minyororo ya maduka na wauzaji wa jumla', en: 'Retail chains and wholesalers' },
  plan_ent_desc:       { sw: 'Kwa biashara zinazohitaji usaidizi mahususi na uunganishaji wa API.',
                          en: 'For retail chains and wholesalers that need dedicated support.' },

  // ── FAQ ──────────────────────────────────────────────────────────────────────
  faq_label:       { sw: '04 · MASWALI',          en: '04 · FAQ'            },
  faq_h2:          { sw: 'Maswali ya kawaida.',   en: 'Common questions.'   },
  faq_still:       { sw: 'Bado una maswali?',     en: 'Still have questions?' },
  faq_team:        { sw: 'Zungumza na timu moja kwa moja — tunajibu haraka.', en: 'Talk to the team directly — we respond fast.' },
  faq_wa:          { sw: 'Piga gumzo WhatsApp →', en: 'Chat on WhatsApp →'  },
  faq_q1:          { sw: 'Je, Ziada inafanya kazi bila mtandao?',            en: 'Does Ziada work without internet?'           },
  faq_a1:          { sw: 'Ndiyo. Ziada inafanya kazi bila mtandao kwanza — unaweza kufanya mauzo, kusasisha hifadhi na kufuatilia mikopo bila muunganisho. Kila kitu kinasawazishwa kiotomatiki unapounganika tena.',
                     en: "Yes. Ziada is offline-first — you can ring up sales, update stock and track credits with no connection. Everything syncs automatically the moment you're back online." },
  faq_q2:          { sw: 'Naweza kuongeza bidhaa ngapi?',                    en: 'How many products can I add?'               },
  faq_a2:          { sw: 'Mipango ya Starter inasaidia bidhaa hadi 500. Mipango ya Business na Enterprise haina kikomo. Bidhaa zinaweza kuwa na aina mbalimbali (ukubwa, rangi) na viwango vya bei ya jumla.',
                     en: 'Starter plans support up to 500 products. Business and Enterprise plans have no limit. Products can have multiple variants (sizes, colours) and bulk pricing tiers.' },
  faq_q3:          { sw: 'Naweza kusimamia maduka mengi?',                   en: 'Can I manage multiple stores?'              },
  faq_a3:          { sw: 'Ndiyo. Mpango wa Business unasaidia hadi maeneo 3 kutoka dashibodi moja, ikiwa ni pamoja na uhamishaji wa hifadhi kati ya maduka na uchambuzi uliounganishwa. Enterprise inasaidia maduka yasiyokuwa na kikomo.',
                     en: 'Yes. The Business plan supports up to 3 locations from one dashboard, including cross-store stock transfers and consolidated analytics. Enterprise supports unlimited stores.' },
  faq_q4:          { sw: 'Wateja wangu wanaweza kutumia njia gani za malipo?', en: 'What payment methods can my customers use?' },
  faq_a4:          { sw: 'Pesa taslimu, M-Pesa, Tigo Pesa, Airtel Money na uhamisho wa benki — yote kwenye tiketi moja. Malipo yanaweza kugawanywa kati ya njia mbalimbali kwenye mauzo moja.',
                     en: 'Cash, M-Pesa, Tigo Pesa, Airtel Money and bank transfer — all on one ticket. Payments can be split across methods on a single sale.' },
  faq_q5:          { sw: 'Je, data yangu ni salama na ya faragha?',           en: 'Is my data private and secure?'            },
  faq_a5:          { sw: 'Ndiyo. Data yako ya mauzo, wateja na hifadhi haijawahi kutumika kufunza mfano wowote wa AI. Data inahifadhiwa kwenye seva Tanzania, imesimbwa kwa njia fiche wakati wa kupumzika na kusafiri. Unamiliki data yako na unaweza kuisafirisha wakati wowote.',
                     en: 'Yes. Your sales, customer and stock data is never used to train any AI model. Data is stored on servers in Tanzania, encrypted at rest and in transit. You own your data and can export it any time.' },
  faq_q6:          { sw: 'Jinsi gani ya kufuta usajili wangu?',               en: 'How do I cancel my subscription?'          },
  faq_a6:          { sw: 'Unaweza kufuta wakati wowote kutoka Mipangilio → Bili. Hakuna mikataba ya kufunga, hakuna ada ya kutoka. Data yako inabaki inayoweza kusafirishwa kwa siku 30 baada ya kufuta.',
                     en: 'You can cancel any time from Settings → Billing. No lock-in contracts, no exit fees. Your data remains exportable for 30 days after cancellation.' },

  // ── CTA ──────────────────────────────────────────────────────────────────────
  cta_label:       { sw: '05 · PATA ZIADA',                              en: '05 · GET ZIADA'                         },
  cta_h2:          { sw: 'Endesha duka lako kwa programu tulivu.',       en: 'Run your shop on calm software.'        },
  cta_h2a:         { sw: 'Endesha duka lako kwa',                        en: 'Run your shop on'                       },
  cta_h2b:         { sw: 'programu tulivu.',                             en: 'calm software.'                         },
  cta_sub:         { sw: 'Siku saba, kipengele chochote, bila kadi. Maduka mengi yanaanza Ziada ndani ya saa moja.',
                     en: 'Seven days, every feature, no card. Most shops are live on Ziada in under an hour.'        },
  cta_trial:       { sw: 'Anza majaribio',       en: 'Start trial'       },
  cta_talk:        { sw: 'Zungumza na timu',    en: 'Talk to the team'  },

  // ── Footer ───────────────────────────────────────────────────────────────────
  footer_desc:     { sw: 'Mfumo wa uendeshaji wa biashara. Ilijengwa Dar es Salaam, kwa kila kaunta barani.',
                     en: 'The operating system for retail. Built in Dar es Salaam, made for any counter on the continent.' },
  footer_product:  { sw: 'Bidhaa',    en: 'Product'  },
  footer_company:  { sw: 'Kampuni',   en: 'Company'  },
  footer_legal:    { sw: 'Kisheria',  en: 'Legal'    },
  footer_pos:      { sw: 'Mauzo',     en: 'Point of Sale' },
  footer_inv:      { sw: 'Hifadhi',   en: 'Inventory'     },
  footer_analytics:{ sw: 'Uchambuzi', en: 'Analytics'     },
  footer_credits:  { sw: 'Mikopo',    en: 'Credits'        },
  footer_about:    { sw: 'Kuhusu',    en: 'About'          },
  footer_pricing:  { sw: 'Bei',       en: 'Pricing'        },
  footer_contact:  { sw: 'Wasiliana', en: 'Contact'        },
  footer_careers:  { sw: 'Kazi',      en: 'Careers'        },
  footer_terms:    { sw: 'Masharti ya Huduma', en: 'Terms of Service' },
  footer_privacy:  { sw: 'Sera ya Faragha',    en: 'Privacy Policy'   },
  footer_built:    { sw: 'Ilijengwa na',        en: 'Built by'         },

  // ── Login page ────────────────────────────────────────────────────────────────
  auth_or:              { sw: 'au',                                           en: 'or'                                     },
  auth_login_h1:        { sw: 'Karibu tena',                                  en: 'Welcome back'                           },
  auth_login_sub:       { sw: 'Ingia na namba ya simu na nenosiri lako.',     en: 'Sign in with your phone number and password.' },
  auth_login_phone:     { sw: 'Namba ya simu',                                en: 'Phone number'                           },
  auth_login_password:  { sw: 'Nenosiri',                                     en: 'Password'                               },
  auth_login_forgot:    { sw: 'Umesahau nenosiri?',                           en: 'Forgot password?'                       },
  auth_login_btn:       { sw: 'Ingia →',                                      en: 'Sign in →'                              },
  auth_login_signing:   { sw: 'Inaingia…',                                    en: 'Signing in…'                            },
  auth_login_new:       { sw: 'Mpya Ziada?',                                  en: 'New to Ziada?'                          },
  auth_login_trial_link:{ sw: 'Anza jaribio lako bure la siku 7',             en: 'Start your free 7-day trial'            },

  // ── Register page ─────────────────────────────────────────────────────────────
  auth_reg_h1_0:        { sw: 'Unda akaunti yako',                            en: 'Create your account'                    },
  auth_reg_h1_1:        { sw: 'Sanidi duka lako',                             en: 'Set up your shop'                       },
  auth_reg_sub_0:       { sw: 'Hati zako za kuingia. Anza jaribio lako bure la siku 7.', en: 'Your login credentials. Start your free 7-day trial.' },
  auth_reg_sub_1:       { sw: 'Tuambie kuhusu biashara yako ili tuweke Ziada vizuri kwako.', en: 'Tell us about your business so we can configure Ziada for you.' },
  auth_reg_step:        { sw: 'Hatua',                                        en: 'Step'                                   },
  auth_reg_of:          { sw: 'ya',                                           en: 'of'                                     },
  auth_reg_name:        { sw: 'Jina kamili',                                  en: 'Full name'                              },
  auth_reg_name_hint:   { sw: 'Jina la kwanza na la familia, mfano Hamisi Mwakapaga', en: 'First and last name, e.g. Hamisi Mwakapaga' },
  auth_reg_phone:       { sw: 'Namba ya simu',                                en: 'Phone number'                           },
  auth_reg_phone_hint:  { sw: 'Nambari 10, mfano 0712345678',                 en: '10 digits, e.g. 0712345678'             },
  auth_reg_email:       { sw: 'Barua pepe',                                   en: 'Email'                                  },
  auth_reg_email_hint:  { sw: 'Inatumika kwa risiti na kurejesha akaunti',    en: 'Used for receipts and account recovery' },
  auth_reg_pw:          { sw: 'Nenosiri',                                     en: 'Password'                               },
  auth_reg_confirm:     { sw: 'Thibitisha nenosiri',                          en: 'Confirm password'                       },
  auth_reg_shop:        { sw: 'Jina la duka lako kuu',                        en: 'Your main shop name'                    },
  auth_reg_region:      { sw: 'Mkoa',                                         en: 'Region'                                 },
  auth_reg_btype:       { sw: 'Aina ya biashara',                             en: 'Business type'                          },
  auth_reg_next:        { sw: 'Hatua inayofuata →',                           en: 'Next step →'                            },
  auth_reg_back:        { sw: '← Rudi',                                       en: '← Back'                                 },
  auth_reg_btn:         { sw: 'Anza jaribio bure',                            en: 'Start free trial'                       },
  auth_reg_creating:    { sw: 'Inaunda akaunti…',                             en: 'Creating account…'                      },
  auth_reg_have:        { sw: 'Una akaunti tayari?',                          en: 'Already have an account?'               },
  auth_reg_signin:      { sw: 'Ingia',                                        en: 'Sign in'                                },
  auth_reg_optional:    { sw: '(hiari)',                                      en: '(optional)'                             },
  auth_reg_pw_min:      { sw: 'Angalau herufi 8',                             en: 'Min 8 characters'                       },
  auth_reg_pw_weak:     { sw: 'Dhaifu',                                       en: 'Weak'                                   },
  auth_reg_pw_fair:     { sw: 'Wastani',                                      en: 'Fair'                                   },
  auth_reg_pw_strong:   { sw: 'Imara',                                        en: 'Strong'                                 },
  auth_reg_region_ph:   { sw: 'Andika kutafuta mkoa…',                        en: 'Type to search region…'                 },
  auth_reg_no_region:   { sw: 'Hakuna mkoa unaolingana na',                   en: 'No regions match'                       },

  // ── Activate page ─────────────────────────────────────────────────────────────
  act_acct_created:     { sw: 'AKAUNTI IMEUNDWA',                             en: 'ACCOUNT CREATED'                        },
  act_h1:               { sw: 'Washa jaribio lako la siku 7',                 en: 'Activate your 7-day trial'              },
  act_welcome:          { sw: 'Karibu',                                       en: 'Welcome'                                },
  act_sub:              { sw: 'Akaunti yako iko tayari. Lipa TZS 10,000 kupitia Airtel Money ili kufungua jaribio lako la bure la siku 7.',
                          en: 'Your account is ready. Pay TZS 10,000 via Airtel Money to unlock your free 7-day trial.'   },
  act_payment_hdr:      { sw: 'AIRTEL MONEY — MAELEZO YA MALIPO',             en: 'AIRTEL MONEY — PAYMENT DETAILS'         },
  act_send_to:          { sw: 'TUMA KWA',                                     en: 'SEND TO'                                },
  act_label_name:       { sw: 'JINA',                                         en: 'NAME'                                   },
  act_label_network:    { sw: 'MTANDAO',                                      en: 'NETWORK'                                },
  act_label_amount:     { sw: 'KIASI',                                        en: 'AMOUNT'                                 },
  act_how_to_pay:       { sw: 'JINSI YA KULIPA',                              en: 'HOW TO PAY'                             },
  act_step1_t:          { sw: 'Fungua Airtel Money',                          en: 'Open Airtel Money'                      },
  act_step1_d:          { sw: 'Piga *150*60# au tumia programu yako ya Airtel Money.', en: 'Dial *150*60# or use your Airtel Money app.' },
  act_step2_t:          { sw: 'Tuma TZS 10,000',                             en: 'Send TZS 10,000'                        },
  act_step3_t:          { sw: 'Tuma ujumbe WhatsApp',                        en: 'Message on WhatsApp'                    },
  act_step3_d:          { sw: 'Bonyeza kitufe hapa chini kutuma uthibitisho wa malipo yako.', en: 'Tap the button below to send your payment confirmation.' },
  act_step4_t:          { sw: 'Akaunti imewashwa',                           en: 'Account activated'                      },
  act_step4_d:          { sw: 'Cameltech itawasha jaribio lako ndani ya dakika.', en: 'Cameltech will activate your trial within minutes.' },
  act_wa_btn:           { sw: 'Tuma uthibitisho wa malipo WhatsApp',         en: 'Send payment confirmation on WhatsApp'  },
  act_wa_open:          { sw: 'Inafungua WhatsApp na ujumbe ulioandikwa tayari kwa', en: 'Opens WhatsApp with a pre-filled message to' },
  act_wa_activates:     { sw: 'Jaribio lako litawashwa ndani ya dakika baada ya uthibitisho.', en: 'Your trial activates within minutes of confirmation.' },
  act_waiting:          { sw: 'Inasubiri uanzishwaji',                       en: 'Waiting for activation'                 },
  act_auto_check:       { sw: 'Inakagua kiotomatiki baada ya',               en: 'Auto-checking in'                       },
  act_check_btn:        { sw: 'Kagua sasa',                                  en: 'Check now'                              },
  act_checking:         { sw: 'Inakagua…',                                   en: 'Checking…'                              },
  act_err_server:       { sw: 'Haikuweza kufikia seva. Tafadhali jaribu tena.', en: 'Could not reach the server. Please try again.' },
} as const;

export type TKey = keyof typeof dict;

export function t(lang: Lang, key: TKey): string {
  return dict[key][lang];
}
